# configs/constants.py

DEFAULT_STATE_PORTAL_ABBR = 'NJ'
DEFAULT_COMPANY_NAME_CHECK_ENABLED = True
DEFAULT_DOMAIN_CHECK_ENABLED = True
DEFAULT_DOMAIN_CHECK_LIMIT = 2
DEFAULT_COMPANY_CHECK_LIMIT = 2
DEFAULT_INPUT_DIRECTORY = 'data/input'
DEFAULT_REPORTS_DIRECTORY = 'data/reports'
DEFAULT_REPORT_FILENAME = 'report'
DEFAULT_OUTPUT_FORMAT = 'xls'
DEFAULT_ENABLE_LOGGING_TO_FILE = False
